"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.handlers = exports.auth = exports.SessionProvider = exports.useSession = exports.signOut = exports.signIn = void 0;
var react_1 = require("next-auth/react");
Object.defineProperty(exports, "signIn", { enumerable: true, get: function () { return react_1.signIn; } });
Object.defineProperty(exports, "signOut", { enumerable: true, get: function () { return react_1.signOut; } });
Object.defineProperty(exports, "useSession", { enumerable: true, get: function () { return react_1.useSession; } });
Object.defineProperty(exports, "SessionProvider", { enumerable: true, get: function () { return react_1.SessionProvider; } });
var auth_1 = require("./auth");
Object.defineProperty(exports, "handlers", { enumerable: true, get: function () { return auth_1.handlers; } });
Object.defineProperty(exports, "auth", { enumerable: true, get: function () { return auth_1.auth; } });
